### ISSUE TITLE
Is it possible to run main.py without downloading the full nuScenes dataset?

### ISSUE THREAD

**Issue by alanwanga** [eddyhkchiu/mahalanobis_3d_multi_object_tracking#16]
Hi, thanks for the nice work.

Since the full nuScenes dataset is quite large (360GB), how can I run main.py on the subset of it (e.g mini, part1, part2, etc)?

Best,

**Comment by eddyhkchiu** [comment]
Hi,

Without downloading the full dataset (360GB), running the code with only part1, part2, etc is not possible based on the nuscenes dataset API design. I have tried that before but that did not work.

But it is possible to run the code on the mini set with some extra work:
You will need to change the code in main.py line 659 ~ 673, adding one new case for the mini set. Download the mini set data, decompress, and assign the 'data_root' variable. Assign the 'version' variable to 'v1.0-mini'. You also need to generate one 3d detection result json file for the mini set. 

This can be potentially done by searching for other repositories of nuscenes 3d object detection, and running their code to get the mini set detection result json file. 

Another easier approach is to generate one from megvii_train.json and megvii_val.json.  Because the mini set is a subset of trainval set, you can first write some code to get the 10 scene tokens of the mini set, then extract the detection results of those 10 scene tokens from megvii_train.json and megvii_val.json.

Let me know if you have any questions about the above approach.

**Comment by harryrobotics** [comment]
Actually, if you only need to download the metadata files to run the code. You don't need the images, point cloud files, or radar files.You should change the name of metadata folder : v1.0-trainval-metadata to v1.0-trainval. 
Your dataset folder should be like this: nuscenes/v1.0-trainval
Metadata has all information which you need to run this line of code:
```nusc = NuScenes(version='v1.0-trainval', dataroot='/home/harry/nuscenes/', verbose=True)```

**Comment by eddyhkchiu** [comment]
Thanks for sharing this suggestion!

**Comment by alanwanga** [comment]
It's running. Thank you guys!
